# Generated by Django 4.2.9 on 2024-01-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customuser_name_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '---SELECT---'), (1, 'Male'), (2, 'Female')], max_length=20, null=True),
        ),
    ]
