# Generated by Django 5.0.1 on 2024-02-02 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_menu_submenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymaster',
            name='zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='user.zonemaster'),
        ),
    ]
