# Generated by Django 5.0.1 on 2024-02-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_citymaster_zone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmaster',
            name='zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='user.zonemaster'),
        ),
    ]
