# Generated by Django 5.0.1 on 2024-02-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_regionmaster_zone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemaster',
            name='region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_states', to='user.regionmaster'),
        ),
        migrations.AlterField(
            model_name='statemaster',
            name='zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_states', to='user.zonemaster'),
        ),
    ]
