# Generated by Django 5.0.1 on 2024-02-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_statemaster_region_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymaster',
            name='region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_cities', to='user.regionmaster'),
        ),
        migrations.AlterField(
            model_name='citymaster',
            name='state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_cities', to='user.statemaster'),
        ),
        migrations.AlterField(
            model_name='citymaster',
            name='zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_cities', to='user.zonemaster'),
        ),
    ]
