# Generated by Django 4.2.10 on 2024-02-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_citymaster_region_id_alter_citymaster_state_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '---SELECT---'), ('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
    ]
