# Generated by Django 4.2.10 on 2024-02-29 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_operationteam_remaining_interview_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeteam',
            name='operation_team_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.operationteam'),
        ),
    ]
