# Generated by Django 4.2.10 on 2024-02-27 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('man_days', models.IntegerField(blank=True, null=True)),
                ('total_achievement', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_work_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('remaining_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('reason_for_adjustment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_team_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.operationteam')),
            ],
        ),
    ]
