# Generated by Django 4.2.10 on 2024-02-27 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_operationtask_reason_for_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationteam',
            name='daily_work_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
        migrations.AddField(
            model_name='operationteam',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationteam',
            name='man_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationteam',
            name='reason_for_adjustment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='operationteam',
            name='remaining_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
        migrations.AddField(
            model_name='operationteam',
            name='total_achievement',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
