# Generated by Django 4.2.10 on 2024-02-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_delete_operationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationteam',
            name='project_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
