# Generated by Django 4.2.10 on 2024-02-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_operationteam_project_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationteam',
            name='daily_work_time',
        ),
    ]
