# Generated by Django 4.2.10 on 2024-02-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_remove_operationteam_daily_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationteam',
            name='status',
            field=models.CharField(blank=True, choices=[('', '---SELECT---'), ('setup', 'setup'), ('onhold', 'onhold'), ('inprogress', 'inprogress'), ('completed', 'completed')], max_length=100, null=True),
        ),
    ]
