# Generated by Django 4.2.10 on 2024-02-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_operationteam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationteam',
            name='remaining_interview',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operationteam',
            name='status',
            field=models.CharField(blank=True, choices=[('', '---SELECT---'), ('setup', 'SETUP'), ('onhold', 'ONHOLD'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED')], max_length=100, null=True),
        ),
    ]
