# Generated by Django 5.0.1 on 2024-01-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_user_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
