# Generated by Django 5.0.1 on 2024-01-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_finance_select_project_operation_select'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='set_up',
            new_name='set_up_fee',
        ),
    ]
