# Generated by Django 5.0.1 on 2024-02-05 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_feemaster_remove_project_set_up_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='set_up_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_fee', to='project.feemaster'),
        ),
    ]
