# Generated by Django 5.0.1 on 2024-02-05 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_set_up_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tentative_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
