# Generated by Django 5.0.1 on 2024-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_tentative_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feemaster',
            name='fee_type',
            field=models.CharField(default='transction', max_length=100),
            preserve_default=False,
        ),
    ]
