# Generated by Django 5.0.1 on 2024-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_feemaster_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('project_type1', 'project_type1'), ('project_type2', 'project_type2'), ('project_type3', 'project_type3')], max_length=100, null=True),
        ),
    ]
