# Generated by Django 5.0.1 on 2024-02-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_project_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
    ]
