# Generated by Django 5.0.1 on 2024-02-06 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tentative_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
