# Generated by Django 5.0.1 on 2024-02-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_project_tentative_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
