# Generated by Django 5.0.1 on 2024-02-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_project_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
