# Generated by Django 4.2.9 on 2024-02-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_projecttracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_project_id',
        ),
    ]
