# Generated by Django 4.2.9 on 2024-02-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_projectmanager_project_user_email_project_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_manager', to='project.projectmanager'),
        ),
    ]
