# Generated by Django 4.2.9 on 2024-02-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_alter_project_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
