# Generated by Django 4.2.9 on 2024-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
