# Generated by Django 4.2.9 on 2024-02-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_alter_project_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tentative_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tentative_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
