# Generated by Django 4.2.10 on 2024-02-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_alter_project_tentative_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='upload_document',
            field=models.FileField(blank=True, null=True, upload_to='File Upload'),
        ),
    ]
