# Generated by Django 4.2.10 on 2024-02-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_project_currency_symbol_project_upload_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
    ]
