# Generated by Django 4.2.9 on 2024-02-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_salesowner_client_additional_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
