# Generated by Django 4.2.10 on 2024-02-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_project_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cpi',
        ),
    ]
