# Generated by Django 4.2.10 on 2024-02-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_remove_project_cpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cpi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
