# Generated by Django 4.2.10 on 2024-02-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_project_cpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttracking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='projecttracking',
            name='start_date',
        ),
    ]
