# Generated by Django 4.2.10 on 2024-02-26 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_remove_projecttracking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttracking',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 26, 12, 44, 53, 945043, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
