# Generated by Django 4.2.10 on 2024-02-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_projecttracking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttracking',
            old_name='durations',
            new_name='man_day',
        ),
        migrations.AddField(
            model_name='projecttracking',
            name='target_achieve',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
