# Generated by Django 4.2.10 on 2024-02-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_rename_durations_projecttracking_man_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='currency_symbol',
        ),
        migrations.RemoveField(
            model_name='project',
            name='upload_document',
        ),
        migrations.RemoveField(
            model_name='projecttracking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='projecttracking',
            name='man_day',
        ),
        migrations.RemoveField(
            model_name='projecttracking',
            name='target_achieve',
        ),
        migrations.AddField(
            model_name='client',
            name='additional_survey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_purchase_order_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email_id_for_cc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='other_specific_billing_instruction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='total_survey_to_be_billed_to_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projecttracking',
            name='durations',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cpi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('project_type1', 'project_type1'), ('project_type2', 'project_type2'), ('project_type3', 'project_type3')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='projectType',
        ),
        migrations.AddField(
            model_name='project',
            name='sales_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_owner', to='project.salesowner'),
        ),
    ]
